apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: hello-openobserve
build:
  tagPolicy:
    envTemplate:
      template: "latest"
  artifacts:
    - image: hello-openobserve/api
      context: ./api
  local:
    push: false
    useBuildkit: true
profiles:
  - name: local
    activation:
      - env: ENV=local
      - kubeContext: minikube
        command: dev
    manifests:
      kustomize:
        paths:
          - ./.k8s/overlays/local
        buildArgs: [ "--enable-helm" ]
    deploy:
      kubectl: {}
