apiVersion: v1
kind: Service
metadata:
  name: openobserve
  namespace: openobserve
  labels:
    app: openobserve
spec:
  ports:
    - port: 5080
  selector:
    app: openobserve
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openobserve
  namespace: openobserve
  labels:
    name: openobserve
spec:
  serviceName: openobserve
  replicas: 1
  selector:
    matchLabels:
      app: openobserve
  template:
    metadata:
      labels:
        app: openobserve
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      containers:
        - name: openobserve
          image: public.ecr.aws/zinclabs/openobserve:v0.5.1
          ports:
            - containerPort: 5080
          envFrom:
            - configMapRef:
                name: openobserve-config
          resources:
            limits:
              cpu: 4096m
              memory: 2048Mi
            requests:
              cpu: 256m
              memory: 50Mi
          imagePullPolicy: IfNotPresent
