apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
spec:
  rules:
    - host: "sample-openobserve.localhost.com"
      http:
        paths:
          - path: /app/(api)(\/.*)
            pathType: Prefix
            backend:
              service:
                name: app-api
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openobserve-ingress
  namespace: openobserve
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: "sample-openobserve.localhost.com"
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: openobserve
                port:
                  number: 5080
