resources:
  - ../../base
  - ingress.yaml
patches:
  - target:
      kind: ConfigMap
    path: api/configmap.yaml
helmCharts:
  - name: localstack
    repo: https://localstack.github.io/helm-charts
    version: 0.5.5
    releaseName: localstack
    valuesFile: localstack-values.yaml
