resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
patches:
  - target:
      kind: ConfigMap
    path: api/configmap.yaml
  - target:
      kind: StatefulSet
    path: openobserve/statefulset.yaml
  - target:
      kind: ConfigMap
    path: openobserve/configmap.yaml
helmCharts:
  - name: fluent-bit
    repo: https://fluent.github.io/helm-charts
    version: 0.37.0
    namespace: fluent-bit
    releaseName: fluent-bit
    valuesFile: fluent-bit/values.yaml
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 23.1.0
    namespace: prometheus
    releaseName: prometheus
    valuesFile: prometheus/values.yaml
