resources:
  - ../../base
  - ingress.yaml
patches:
  - target:
      kind: ConfigMap
    path: api/configmap.yaml
  - target:
      kind: StatefulSet
    path: openobserve/statefulset.yaml
  - target:
      kind: ConfigMap
    path: openobserve/configmap.yaml
